export type satcatRow = {
	object_name: string;
	object_id: string;
	norad_cat_id: number;
	object_type: string;
	ops_status_code: string;
	owner: string;
	launch_date: string;
	launch_site: string;
	decay_date: string;
	period: number;
	inclination: number;
	apogee: number;
	perigee: number;
	rcs: number;
	data_status_code: string;
	orbit_center: string;
	docked_norad_cat_id: number;
	orbit_type: string;
};
